sudo: required
dist: trusty

language: cpp

os: linux

compiler: 
    - gcc

cache:
    - ccache
    - apt

addons:
    apt:
        packages:
            - clang-format-3.9

before_install:
    - wget https://media.githubusercontent.com/media/XiaoMi/pegasus-common/master/build-depends.tar.gz
    - tar xfz build-depends.tar.gz
    - rm -f build-depends.tar.gz
    - cd packages
    - ls | xargs sudo dpkg -i --force-depends
    - cd ..

before_script:
    - cd thirdparty
    - wget https://media.githubusercontent.com/media/XiaoMi/pegasus-common/master/pegasus-thirdparty-prebuild.tar.gz
    - tar xfz pegasus-thirdparty-prebuild.tar.gz
    - rm -f pegasus-thirdparty-prebuild.tar.gz
    - cd ..
    - ulimit -c unlimited -S

script:
    - ./run.sh test --skip_thirdparty --check --disable_gperf

after_script:
    - ./run.sh stop_zk

notifications:
    email: false
