sudo: required
dist: trusty

language: cpp

os: linux

compiler: 
    - gcc

before_install:
    - wget https://raw.githubusercontent.com/shengofsun/packages/master/build-depends.tar.gz
    - tar xf build-depends.tar.gz
    - cd packages
    - ls | xargs sudo dpkg -i --force-depends
    - cd ..

install:
    # - ./run.sh format

before_script:
    - cd thirdparty
    - wget https://raw.githubusercontent.com/shengofsun/packages/master/pegasus-thirdparty-prebuild.tar.gz
    - tar xf pegasus-thirdparty-prebuild.tar.gz
    - rm -rf pegasus-thirdparty-prebuild.tar.gz
    - cd ..
    - ulimit -c unlimited -S

script:
    - ./run.sh test

after_script:
    - ./run.sh stop_zk

notifications:
    email: false
