sudo: required
dist: trusty

language: cpp

os: linux

compiler:
    - gcc

addons:
  apt:
    packages:
      - libsnappy-dev
      - liblz4-dev
      - clang-format-3.9

cache:
    - ccache
    - apt

before_install:
    - wget https://github.com/XiaoMi/pegasus-common/releases/download/deps/build-depends.tar.gz
    - tar xfz build-depends.tar.gz
    - rm -f build-depends.tar.gz
    - cd packages
    - ls | xargs sudo dpkg -i --force-depends
    - cd ..

install:
    - wget https://github.com/facebook/zstd/archive/v1.3.7.zip; unzip v1.3.7; cd zstd-1.3.7;
    - mkdir cmake-build; cd cmake-build; cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -DZSTD_BUILD_PROGRAMS=OFF ../build/cmake; sudo make install -j8;
    - cd ../..
    - rm -rf v1.3.7.zip zstd-1.3.7;

before_script:
    - cd rdsn/thirdparty
    - wget https://github.com/XiaoMi/pegasus-common/releases/download/deps/pegasus-thirdparty-prebuild.zip
    - unzip pegasus-thirdparty-prebuild.zip
    - rm -f pegasus-thirdparty-prebuild.zip
    - cd ../..
    - ulimit -c unlimited -S

script:
    - ./scripts/travis.sh

after_script:
    - ./run.sh stop_zk

notifications:
    email: false
