#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Test - java client
on:
  pull_request:
    branches:
        - master
        - 'v[0-9]+.*' # release branch
        - ci-test # testing branch for github action
        - '*dev'      # developing branch
    paths:
      - .github/workflows/lint_and_test_java-client.yml
      - java-client/**

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  spotless:
    name: Spotless
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: spotless
        working-directory: ./java-client
        run: mvn spotless:check

  build_server:
    name: Build server
    needs: spotless
    runs-on: ubuntu-latest
    env:
      USE_JEMALLOC: OFF
      ARTIFACT_NAME: release_for_java_client
      BUILD_OPTIONS: -t release
    container:
      image: apache/pegasus:thirdparties-bin-test-ubuntu2204-${{ github.base_ref }}
    steps:
      - uses: actions/checkout@v4
      - name: Rebuild thirdparty if needed
        uses: "./.github/actions/rebuild_thirdparty_if_needed"
      - name: Build Pegasus
        uses: "./.github/actions/build_pegasus"
      - name: Upload artifact
        uses: "./.github/actions/upload_artifact"

  test_java_client:
    name: Test Java client
    needs: build_server
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: release_for_java_client
    container:
      image: apache/pegasus:thirdparties-bin-test-ubuntu2204-${{ github.base_ref }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Download artifact
        uses: "./.github/actions/download_artifact"
      - name: Start Pegasus cluster
        run: |
          apt-get update
          apt-get install net-tools -y
          export LD_LIBRARY_PATH=$(pwd)/thirdparty/output/lib:${JAVA_HOME}/jre/lib/amd64/server
          ulimit -s unlimited
          ./run.sh start_onebox
      - name: Download thrift
        working-directory: ./java-client/scripts
        run: ./download_thrift.sh
      - name: Run Java client tests
        working-directory: ./java-client
        run: mvn test --no-transfer-progress
